/* tslint:disable */
/* eslint-disable */
/**
 * auth-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact:
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import { UserFromJSON, UserFromJSONTyped, UserToJSON } from './User';

/**
 *
 * @export
 * @interface AddUserResponse
 */
export interface AddUserResponse {
    /**
     *
     * @type {User}
     * @memberof AddUserResponse
     */
    user: User;
}

/**
 * Check if a given object implements the AddUserResponse interface.
 */
export function instanceOfAddUserResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'user' in value;

    return isInstance;
}

export function AddUserResponseFromJSON(json: any): AddUserResponse {
    return AddUserResponseFromJSONTyped(json, false);
}

export function AddUserResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AddUserResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        user: UserFromJSON(json['user']),
    };
}

export function AddUserResponseToJSON(value?: AddUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        user: UserToJSON(value.user),
    };
}
