/* tslint:disable */
/* eslint-disable */
/**
 * auth-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact:
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthSuccessResponse
 */
export interface AuthSuccessResponse {
    /**
     *
     * @type {string}
     * @memberof AuthSuccessResponse
     */
    token: string;
}

/**
 * Check if a given object implements the AuthSuccessResponse interface.
 */
export function instanceOfAuthSuccessResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'token' in value;

    return isInstance;
}

export function AuthSuccessResponseFromJSON(json: any): AuthSuccessResponse {
    return AuthSuccessResponseFromJSONTyped(json, false);
}

export function AuthSuccessResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AuthSuccessResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        token: json['token'],
    };
}

export function AuthSuccessResponseToJSON(
    value?: AuthSuccessResponse | null,
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        token: value.token,
    };
}
