/* tslint:disable */
/* eslint-disable */
/**
 * auth-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact:
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {Date}
     * @memberof User
     */
    createdUtc: Date;
    /**
     *
     * @type {boolean}
     * @memberof User
     */
    isAdmin: boolean;
    /**
     *
     * @type {Date}
     * @memberof User
     */
    updatedUtc: Date;
    /**
     *
     * @type {string}
     * @memberof User
     */
    userId: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    username: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && 'createdUtc' in value;
    isInstance = isInstance && 'isAdmin' in value;
    isInstance = isInstance && 'updatedUtc' in value;
    isInstance = isInstance && 'userId' in value;
    isInstance = isInstance && 'username' in value;

    return isInstance;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): User {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        createdUtc: new Date(json['created_utc']),
        isAdmin: json['is_admin'],
        updatedUtc: new Date(json['updated_utc']),
        userId: json['user_id'],
        username: json['username'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        created_utc: value.createdUtc.toISOString(),
        is_admin: value.isAdmin,
        updated_utc: value.updatedUtc.toISOString(),
        user_id: value.userId,
        username: value.username,
    };
}
